_prefs: 
  baselayer: ''
  mapid: spotbrooklyn.8edc31f9
  saveCenter: true
_properties: {}
attribution: Map data © OpenStreetMap contributors
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -73.9696
  - 40.6527
  - 16
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 0
name: sbk
source: "mapbox:///mapbox.mapbox-streets-v4"
styles: 
  - style.mss
template: ''
