_prefs: 
  baselayer: ''
  saveCenter: true
_properties: {}
attribution: Map data © OpenStreetMap contributors
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -73.9764404296875
  - 40.653294576616204
  - 16
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 0
mtime: 1404145754763
name: sbk
scale: 2
source: "mapbox:///mapbox.mapbox-streets-v4"
styles: 
  - style.mss
template: ''
